#!/bin/bash

set -e

# Run from the repository root, whatever the caller's working directory is, so
# the config path below always resolves.
cd "$(dirname "$0")/.."

CPP_DIRS=(
  # shared C++
  "package/cpp"
  # Android JNI adapter
  "package/android/src/main/cpp"
  # iOS — Objective-C / Objective-C++ bridging files, if any
  "package/ios"
)

# Note: package/nitrogen is generated by nitrogen and git-ignored. It is never
# formatted here — regenerating it would undo the changes anyway.

if which clang-format >/dev/null; then
  DIRS=$(printf "%s " "${CPP_DIRS[@]}")
  find $DIRS -type f \( -name "*.h" -o -name "*.hpp" -o -name "*.cpp" -o -name "*.m" -o -name "*.mm" -o -name "*.c" \) -print0 | while read -d $'\0' file; do
    clang-format -style=file:./config/.clang-format -i "$file"
  done
  echo "C++ Format done!"
else
  echo "error: clang-format not installed, install with 'brew install clang-format' (or manually from https://clang.llvm.org/docs/ClangFormat.html )"
  exit 1
fi
