require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

# Helpers are lambdas in local variables rather than top-level `def`s: CocoaPods
# evaluates a podspec with `eval`, and a method defined that way is not visible
# from inside the `Pod::Spec.new` block on every Ruby / CocoaPods combination
# (Ruby 4.0 + CocoaPods 1.17 raises `undefined method ... for module Pod`).
better_maps_podfile_properties = lambda do
  installation_root = Pod::Config.instance.installation_root
  next {} if installation_root.nil?

  podfile_properties_path = File.join(installation_root, 'Podfile.properties.json')
  next {} unless File.exist?(podfile_properties_path)

  JSON.parse(File.read(podfile_properties_path))
rescue StandardError => e
  Pod::UI.warn "[react-native-better-maps] Failed to read Podfile.properties.json: #{e.message}. iOS Google Maps provider will be disabled."
  {}
end

# Must match IOS_GOOGLE_PROVIDER_PODFILE_PROPERTY in plugin/src/ios.ts
better_maps_ios_google_provider_enabled =
  better_maps_podfile_properties.call['betterMaps.iosGoogleProvider'] == 'true'

Pod::Spec.new do |s|
  s.name         = 'react-native-better-maps'
  s.version      = package['version']
  s.summary      = package['description']
  s.homepage     = package['homepage']
  s.license      = package['license']
  s.authors      = package['author']

  s.platforms    = { :ios => '16.0' }
  s.source       = { :git => package['repository']['url'], :tag => "#{s.version}" }

  # Must match nitro.json ios.iosModuleName so Nitrogen's Swift/C++ bridge finds NitroMaps-Swift.h
  s.module_name  = 'NitroMaps'

  s.source_files = [
    'ios/**/*.{swift}',
    'ios/**/*.{m,mm}',
    'cpp/**/*.{hpp,cpp}',
  ]
  s.exclude_files = [
    'ios/Package.swift',
    'ios/Tests/**/*',
  ]

  s.frameworks = 'MapKit', 'CoreLocation'

  s.dependency 'React-jsi'
  s.dependency 'React-callinvoker'
  if better_maps_ios_google_provider_enabled
    s.dependency 'GoogleMaps'
  end

  # Add all files generated by Nitrogen
  load 'nitrogen/generated/ios/NitroMaps+autolinking.rb'
  add_nitrogen_files(s)

  install_modules_dependencies(s)

  s.test_spec 'Tests' do |test_spec|
    test_spec.source_files = 'iosTests/**/*.swift'
  end
end
